version: "3.7"

services:
    dev:
        image: ruby:2.7.1
        command: ["scripts/run.sh"]
        working_dir: "/srv/jekyll"
        ports:
            - "4000:4000"
            - "35729:35729"
        volumes:
            - ".:/srv/jekyll"
