name: Publish to GH Pages

on:
  push:
  # branches:
  #   - "main"

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Install requirements
        run: pip install -r requirements.txt
